[package]
name = "http_serv"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["log", "threading"]
log = ["dep:pretty_env_logger", "dep:log"]
threading = ["dep:num_cpus", "dep:threadpool"]

[dependencies]
log = { version = "0.4.20", optional = true }
num_cpus = { version = "1.16.0", optional = true }
pretty_env_logger = { version = "0.5.0", optional = true }
threadpool = { version = "1.8.1", optional = true }

